### ISSUE TITLE
no module named disnake

### ISSUE THREAD

**Issue by derdodokoenig** [iy4vet/minecraft-server-discord-bot-python#11]
When I try to start the bot over Visual studio code it doesn't find disnake, I tried downloading it but it just wont accept it.
There are some other errors like 
`from disnake.ext import commands
from dotenv import load_dotenv
from mcrcon import MCRcon`
it can't find disnake.ext, dotenv and mcrcon, when I hower over them it says `Import "mcrcon" could not be resolved` and that is on every single error

**Comment by derdodokoenig** [comment]
> are you using a virtual environment? if not, do you by chance have multiple python installations? maybe vscode's using a different python from what you have in PATH...

Yes, that was the problem thanks but why does it no recognise that I activated recon eventhough I did an set a password?

**Comment by iy4vet** [comment]
so if I understand correctly, it's able to import the mcrcon library now.

for rcon, there's actually 4 relevant settings in the server.properties file of the minecraft server:
- broadcast-rcon-to-ops: this essentially shows server operators the output of rcon commands ("set time to 0", "teleported x to y", etc). not really relevant to the bot though.
- enable-rcon: default is "false", you should set it to "true".
- rcon.password: this I think you've already set up, it just needs to not be empty.
- rcon.port: the network port on which rcon interfaces. its default value is 25575. you just need to make sure it's not the same port as the server port.

please check these in your server.properties file and let me know :)

**Comment by derdodokoenig** [comment]
> so if I understand correctly, it's able to import the mcrcon library now. for rcon, there's actually 4 relevant settings in the server.properties file of the minecraft server: - broadcast-rcon-to-ops: this essentially shows server operators the output of rcon commands ("set time to 0", "teleported x to y", etc). not really relevant to the bot though. - enable-rcon: default is "false", you should set it to "true". - rcon.password: this I think you've already set up, it just needs to not be empty. - rcon.port: the network port on which rcon interfaces. its default value is 25575. you just need to make sure it's not the same port as the server port. please check these in your server.properties file and let me know :)

So I did all of this but i won't work I also opened the ports in the Firewall so the 25575 with UDP and TCP but it just doesn't work, by the way in the .env file there is a _Server Op_ "Slot" do I need to put the discord or the Minecraft ID

**Comment by iy4vet** [comment]
alright…

when you start the server, do you get a line saying "Thread RCON Listener started", followed by a line saying "RCON running on xx.xx.xx.xx:port"?

I'm going through the code to figure out where it gets the IP address from - seems like it's from server.properties, so the server address set in bot.env shouldn't matter.

re: server-op, you'll want to put your discord user id there. if you want more than one, separate each id with a comma.

**Comment by derdodokoenig** [comment]
So if I start the bot over a .bat file it says `ECHO ist eingeschaltet (ON).

C:\Users\(Name)\Desktop\code\Discord bots\Server Starter\GH Bot\minecraft-server-discord-bot-python-2.2>Python bot.py
C:\Users\(Name)\Desktop\code\Discord bots\Server Starter\GH Bot\minecraft-server-discord-bot-python-2.2\bot.py:15: DeprecationWarning: sync_commands_debug is deprecated and will be removed in a future version. Use `command_sync_flags` with an `CommandSyncFlags` instance as a replacement.
  mcBot = commands.Bot(sync_commands_debug=True)
C:\Users\tomwi\Desktop\code\Discord bots\Server Starter\GH Bot\minecraft-server-discord-bot-python-2.2\bot.py:15: DeprecationWarning: Using `command_prefix=None` is deprecated and will result in an error in future versions. If you don't need any prefix functionality, consider using InteractionBot.
  mcBot = commands.Bot(sync_commands_debug=True)
Rcon is not enabled in your server.properties file. Please change enable-rcon to true.
`

**Comment by iy4vet** [comment]
so that tells me that either enable-rcon is still somehow false in the server.properties file, or that the bot isn't seeing the server that you're trying to set up up.

please note, bot.py and bot.env need to be in the same folder as server.jar (or whatever its name is) and server.properties. at present, the bot does not support the servers being in a different location.

**Comment by derdodokoenig** [comment]
> so that tells me that either enable-rcon is still somehow false in the server.properties file, or that the bot isn't seeing the server that you're trying to set up up. please note, bot.py and bot.env need to be in the same folder as server.jar (or whatever its name is) and server.properties. at present, the bot does not support the servers being in a different location.

yes that helped but there a many flaws in the user manuel I've put the rcon password in the properti file but it still says: No password was set.

**Comment by iy4vet** [comment]
no password is set… what did you set as the password? are you sure you saved it?

**Comment by derdodokoenig** [comment]
> no password is set… what did you set as the password? are you sure you saved it?

i've set 1337 in the file from the server

**Comment by derdodokoenig** [comment]
No its alright got it right, I only can start it but it isnt too bad


iy4vet ***@***.***> schrieb am Fr., 31. Mai 2024, 20:06:
